### ISSUE TITLE
Image paths not working

### ISSUE THREAD

**Issue by devinsays** [bluepeter/gatsby-material-ui-business-starter#2]
Hi. Just getting started with Gatsby and was trying out your theme. With a fresh clone of the repo, images aren't loading.

Looks like I can adjust the path in the markdown files and it works.

i.e. `image: "products/jakob-owens-235219-unsplash.jpg"` > `image: "images/products/jakob-owens-235219-unsplash.jpg"`

Just wondering if this is something on your side, or if I missed a build a step or something.

Cheers!

**Comment by bluepeter** [comment]
That's odd. Thanks. I will look into it a little later.

**Comment by bluepeter** [comment]
When you cloned the repo, did you rename it to something else? If so, you should adjust `pathPrefix` in `gatsby-config.js` to use the new name.

**Comment by HenrikGr** [comment]
Had the same problem but changing pathPrefix worked. Thanx.

**Comment by devinsays** [comment]
Thanks for the super quick response! I had not changed the directory name. These were my install steps:

* `git clone git@github.com:bluepeter/gatsby-material-ui-business-starter.git`
* `cd gatsby-material-ui-business-starter/`
* `npm install`
* `gatsby develop`

Just ran through it again to make sure I could reproduce.

I guessed `gatsby build` might need to run before `gatsby develop`, but that also didn't resolve it.

Are you not able to reproduce on your end? Perhaps it is an issue with my environment somewhere....

**Comment by HenrikGr** [comment]
Sorry. It looked like it worked for me by changing the pathPrefix but it did not.
I also read up on that here: https://www.gatsbyjs.org/docs/path-prefix/

After that I'm unsure if that is needed in the gatsby-config.js file?

**Comment by bluepeter** [comment]
Thanks, I will dig into it a little more. I am unable to reproduce the issue in either develop or PROD (i.e., the Github pages deployment).

**Comment by bluepeter** [comment]
Hi @HenrikGr @devinsays please do a `git pull` and try again (I moved the images to `static` per https://www.gatsbyjs.org/docs/adding-images-fonts-files/ recommendation). If this also doesn't work for you, there are a few other options referenced in that file that I can try.

Also, per https://www.npmjs.com/package/gatsby-cli, try not to use `gatsby` commands directly. Instead, use `yarn run develop` (or `npm run develop`) instead.

**Comment by bluepeter** [comment]
Ugh, hang on, the images are now broken for me when I deployed to PROD. Hang on a sec.

**Comment by bluepeter** [comment]
Ok guys, give it a try now. Remember to use `yarn run develop` (instead of gatsby commands).

**Comment by HenrikGr** [comment]
It works now, by moving all image files into the folders for the markup files and change the paths in the markup files.

When I run npm run develop the image files is found in the public/static folder.

**Comment by devinsays** [comment]
Just tested, everything working for me now with a fresh clone and following updated instructions in docs. Thanks @bluepeter. 🍻
