### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by devinsays** [bluepeter/gatsby-material-ui-business-starter#3]
Hey @bluepeter.

Curious why you chose to use `import { Grid, Row, Col } from "react-flexbox-grid";` rather than `import Grid from '@material-ui/core/Grid';`?

Looks like same layout could be achieved with the Material UI Grid, would just need a maxWidth applied (either with a class or inline style).

If this is something you're interested in switching, let me know and I'll send you a pull request.

**Comment by bluepeter** [comment]
Sure, go for it. Let's see how it performs. I found `react-flexbox-grid` to offer a bit more flexibility overall... but that flexibility need may be from a more complex implementation, rather than this reduced use.

**Comment by devinsays** [comment]
Sorry it took me so long to get this. Created a pull request: https://github.com/bluepeter/gatsby-material-ui-business-starter/pull/4

Probably needs a little more testing. And if you try it out and prefer the current your way, no worries at all.

**Comment by bluepeter** [comment]
Closed in https://github.com/bluepeter/gatsby-material-ui-business-starter/pull/4
